-- MYSQL_ADMIN_USER
CREATE USER '${MYSQL_ADMIN_USER}'@'%' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';
CREATE USER '${MYSQL_ADMIN_USER}'@'localhost' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';

-- MYSQL_USER_ONE
CREATE USER '${MYSQL_USER_ONE}'@'%' IDENTIFIED BY '${MYSQL_USER_ONE_PASSWORD}';
CREATE USER '${MYSQL_USER_ONE}'@'localhost' IDENTIFIED BY '${MYSQL_USER_ONE_PASSWORD}';
